version: "3.9"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
  rabbitmq:
    image: "rabbitmq"
    ports:
      - "5672:5672"